export enum UserRole {
  ADMIN = 'ADMIN',
  PROFISSIONAL_SAUDE = 'PROFISSIONAL_SAUDE',
  RECEPCIONISTA = 'RECEPCIONISTA',
}

export enum HeathProfessionalRole {
  MEDICO = 'MEDICO',
  FISIOTERAPEUTA = 'FISIOTERAPEUTA',
  PSICOLOGO = 'PSICOLOGO',
  ENFERMEIRO = 'ENFERMEIRO',
  ARTETERAPEUTA = 'ARTETERAPEUTA',
  TERAPEUTA_OCUPACIONAL = 'TERAPEUTA_OCUPACIONAL',
  FONOAUDIOLOGO = 'FONOAUDIOLOGO',
  ASSISTENTE_SOCIAL = 'ASSISTENTE_SOCIAL',
}
